/**
 * CogniX Capability Registry — canonical `CAP-*` identity and relationships (ADR-052).
 *
 * ── What belongs in this file, and what does not ────────────────────────────
 * This registry is DELIBERATELY COMPACT. An entry carries identity, placement,
 * relationships, the two stored maturity dimensions, and a bounded summary — everything
 * a capability card, a filter or a search result needs, and nothing else.
 *
 * It is NOT a documentation store. Descriptions, architecture, evidence, demo paths,
 * market context and the rest of the ATL-03 payload live in per-capability knowledge
 * modules under `content/atlas/capabilities/`, loaded on demand and referenced here only
 * by `knowledge_ref`. That boundary is what lets ATL-03 author deep knowledge for every
 * capability without this file growing without bound or its schema changing.
 *
 * Adding prose fields here is a defect, not a convenience.
 *
 * ── Population status ───────────────────────────────────────────────────────
 * ATL-02 seeds only the MINIMUM REPRESENTATIVE SET needed to prove the contracts, APIs,
 * relationship resolution, retrieval, provenance and tests. It is NOT the full inventory.
 * ATL-01 identified 33 capabilities; 8 are registered here, chosen to exercise every
 * structural case the model must survive:
 *
 *   • CAP-FORECAST-STABILITY / -DECISION-GAP / -DECISION-WINDOW / -DECISION-REGRET
 *     One work package (DDF-01) delivering FOUR independently addressable capabilities.
 *     This is the cardinality case that decided ADR-052 (AC-ATL-02-9).
 *   • CAP-OBSERVATION-CORRESPONDENCE
 *     The inverse: ONE capability delivered across TWO work packages (CDI-08 + ESF-6).
 *   • CAP-COMMITMENT-INTELLIGENCE
 *     All three registry relationship types at once (SOL-*, EXP-*, PAT-*).
 *   • CAP-SHARED-DECISION-STATE
 *     An unregistered capability — real, contracted, tested, and in no SOL/EXP registry.
 *     ATL-01 found twenty of these; ADR-045 Amendment A exists because of them.
 *   • CAP-CURIOSITY-QUESTIONS
 *     An `experience` capability whose own content is the ADR-046 migration target.
 *
 * ATL-03 populates the remaining 25 and authors knowledge modules. Do not treat the
 * absence of a capability here as evidence it does not exist — see the ATL-01 inventory.
 *
 * ── Platform capabilities carry NO domain ───────────────────────────────────
 * `config/domains.ts` is a catalogue of INDUSTRY domains. It has no cross-domain or
 * platform entry, and adding a pseudo-domain to it to house platform capabilities would
 * pollute an industry catalogue to satisfy the Atlas. A platform capability therefore
 * carries `domains: []`, and its reach is expressed by `platform_reusable` plus the
 * `cross_domain_applicability` assessment in its knowledge module. "Which capabilities are
 * reusable?" is a `platform_reusable=true` filter, not a domain lookup.
 *
 * Governed by: CAPABILITY_KNOWLEDGE_MODEL.md · ADR-045 (as amended) · ADR-046 · ADR-047 · ADR-052
 */

import type { CapabilityIdentity } from '../packages/contracts/src/capability-atlas-model';

export const CAPABILITY_REGISTRY: CapabilityIdentity[] = [
  {
    capability_id: 'CAP-FORECAST-STABILITY',
    name: 'Forecast Stability Intelligence',
    summary: 'States whether the demand outlook is likely to remain materially unchanged, as distinct from whether the model is reliable.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'demand_planner'],
    business_problems: ['bp-forecast-uncertainty'],
    tags: ['detection', 'forecasting', 'explanation'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['DDF-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-forecast-stability',
    owner: 'Demand Observability & Decision Intelligence',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-GAP',
    name: 'Decision Gap Intelligence',
    summary: 'The difference between the commercial opportunity currently emerging and the organisation’s ability to capture it under existing commitments and constraints.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'demand_planner', 'coo'],
    business_problems: ['bp-forecast-uncertainty', 'bp-supplier-reliability'],
    tags: ['detection', 'diagnosis', 'recommendation'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['DDF-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-gap',
    owner: 'Demand Observability & Decision Intelligence',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-WINDOW',
    name: 'Decision Window',
    summary: 'The period during which an intervention can still materially capture or protect the emerging opportunity, derived from a declared operational constraint.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'coo'],
    business_problems: ['bp-decision-latency'],
    tags: ['detection', 'recommendation'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['DDF-01'],
    lifecycle_state: 'Prototype',
    /**
     * Partially implemented, not implemented: every constraint in the estate is a
     * MODELLED_DEMO_ASSUMPTION rather than an observed operational cut-off (ADR-042).
     * The field-level detail is in the knowledge module.
     */
    implementation_status: 'partially-implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-window',
    owner: 'Demand Observability & Decision Intelligence',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-REGRET',
    name: 'Decision Regret Intelligence',
    summary: 'The expected economic consequence of choosing an inferior action, comparing Act Now, Wait and Do Nothing from shared inputs. Not forecast-error cost.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'demand_planner'],
    business_problems: ['bp-decision-latency', 'bp-forecast-uncertainty'],
    tags: ['recommendation', 'simulation', 'explanation'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['DDF-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-regret',
    owner: 'Demand Observability & Decision Intelligence',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-OBSERVATION-CORRESPONDENCE',
    name: 'Observation Correspondence & Attested Admission',
    summary: 'Determines whether an observation addresses the decision that was contracted, against what tolerance, and whether its source carries authority.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['cdao', 'decision_scientist'],
    business_problems: ['bp-ai-trust'],
    tags: ['audit-trail', 'human-in-the-loop', 'detection'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    /** One capability, two work packages — the inverse cardinality case (ADR-052). */
    delivered_by: ['CDI-08', 'ESF-6'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-observation-correspondence',
    owner: 'Enterprise Signal & Decision Contract',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-COMMITMENT-INTELLIGENCE',
    name: 'Commitment Intelligence',
    summary: 'Detects where a promise the enterprise has made will break before the customer experiences it, by propagating commitments across the operating chain.',
    capability_type: 'platform-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'coo', 'supply_chain_planner'],
    business_problems: ['bp-supplier-reliability', 'bp-decision-latency'],
    tags: ['detection', 'diagnosis', 'recommendation'],
    /** All three registry relationship types at once. */
    demonstrated_by: ['SOL-PROMO-01'],
    originated_as: ['EXP-COMMITMENT-01'],
    evidenced_by: ['PAT-COMM-01'],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'partially-implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-commitment-intelligence',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-SHARED-DECISION-STATE',
    name: 'Shared Decision State',
    summary: 'One decision state shared across every CogniX surface, so a scenario changed in one place is the same decision everywhere else.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['enterprise_architect', 'cdao'],
    business_problems: ['bp-decision-latency'],
    tags: ['nextjs-api', 'audit-trail'],
    /** Unregistered: real, contracted and tested, and in no SOL or EXP registry (ADR-045 Amendment A). */
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP10-C'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-shared-decision-state',
    owner: 'Adaptive Intelligence & Service Architecture',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-CURIOSITY-QUESTIONS',
    name: 'Questions Worth Asking',
    summary: 'Curiosity-led entry into the estate: provocative enterprise questions that route to the experiment or solution able to answer them.',
    capability_type: 'experience',
    domains: [],
    personas: ['exec'],
    business_problems: ['bp-capability-discovery'],
    tags: ['enablement', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP6'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-curiosity-questions',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-16',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-PROMOTION-INTELLIGENCE',
    name: 'Promotion Intelligence',
    summary: 'Tests whether promotional uplift projections are compatible with end-to-end supply chain capacity, surfacing the commercial opportunity at risk of a fulfilment bottleneck.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'marketing_strategist', 'supply_chain_planner'],
    business_problems: ['bp-promotion-effectiveness', 'bp-supplier-reliability'],
    tags: ['detection', 'simulation', 'recommendation'],
    demonstrated_by: ['SOL-PROMO-01'],
    originated_as: ['EXP-CDI-01'],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-promotion-intelligence',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DEMAND-FORECAST',
    name: 'Demand & Forecast Intelligence',
    summary: 'Multi-horizon demand forecasting that anticipates micro-regional demand shifts early, and the surface on which the four Demand Decision Frontier capabilities are presented.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'demand_planner', 'category_manager'],
    business_problems: ['bp-forecast-uncertainty'],
    tags: ['forecasting', 'detection', 'explanation'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-demand-forecast',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-PREDICTIVE-INVENTORY',
    name: 'Predictive Inventory Intelligence',
    summary: 'Identifies where inventory buffers will fail first under current lead times and demand velocity, quantifying revenue exposure over the coming days.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['coo', 'supply_chain_manager', 'fulfillment_manager'],
    business_problems: ['bp-stock-availability'],
    tags: ['detection', 'diagnosis', 'static-content'],
    demonstrated_by: ['SOL-INV-03'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'partially-implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-predictive-inventory',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-CATEGORY-INTELLIGENCE',
    name: 'Category Intelligence',
    summary: 'Separates net profit growth from volume growth across category sub-segments and regions, exposing where margin expansion and shrinkage diverge.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['category_manager', 'exec', 'bi_analyst'],
    business_problems: ['bp-margin-compression'],
    tags: ['diagnosis', 'reporting', 'static-content'],
    demonstrated_by: ['SOL-CAT-04'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'partially-implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-category-intelligence',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-RIPPLE',
    name: 'Decision Ripple Intelligence',
    summary: 'Propagates a commercial decision through second- and third-order consequences in adjacent functions, so a marketing choice shows its distribution-centre and margin effects.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'coo', 'cco'],
    business_problems: ['bp-decision-latency'],
    tags: ['diagnosis', 'simulation', 'explanation'],
    demonstrated_by: [],
    originated_as: ['EXP-RIPPLE-02'],
    evidenced_by: ['PAT-RIPPLE-04'],
    delivered_by: [],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-ripple',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-ENTERPRISE-MEMORY',
    name: 'Enterprise Memory Foundation',
    summary: 'Retains what the organisation learned from past operational anomalies so that recurring situations recall their prior resolution and outcome instead of being re-analysed.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'cdao', 'decision_scientist'],
    business_problems: ['bp-decision-recall'],
    tags: ['explanation', 'audit-trail', 'enablement'],
    demonstrated_by: [],
    originated_as: ['EXP-MEMORY-03'],
    evidenced_by: [],
    delivered_by: ['WP10-D'],
    lifecycle_state: 'Concept',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-enterprise-memory',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-OPPORTUNITY-INTELLIGENCE',
    name: 'Opportunity Intelligence',
    summary: 'Looks for hidden upside created by favourable variance, rather than monitoring only risk alerts and negative variance as legacy enterprise monitoring does.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'cco', 'marketing_strategist'],
    business_problems: ['bp-decision-latency'],
    tags: ['detection', 'recommendation', 'static-content'],
    demonstrated_by: [],
    originated_as: ['EXP-OPPORTUNITY-04'],
    evidenced_by: ['PAT-OPP-02'],
    delivered_by: [],
    lifecycle_state: 'Concept',
    implementation_status: 'simulated',
    platform_reusable: true,
    knowledge_ref: 'cap-opportunity-intelligence',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-CAMPAIGN-DECISION',
    name: 'Campaign Decision Intelligence',
    summary: 'The decision capability behind a campaign: whether to intervene, what, where, when and how, rather than collapsing the question into a discount calculator.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['exec', 'marketing_strategist', 'category_manager'],
    business_problems: ['bp-promotion-effectiveness', 'bp-decision-latency'],
    tags: ['recommendation', 'simulation', 'diagnosis'],
    demonstrated_by: ['SOL-PROMO-01'],
    originated_as: ['EXP-CDI-01'],
    evidenced_by: [],
    delivered_by: ['CDI-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-campaign-decision',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-COUNTERFACTUAL-BASELINE',
    name: 'Counterfactual Baseline & Causal Engine',
    summary: 'Separates current baseline, expected-without-intervention and predicted-with-intervention, so a campaign is judged against what would have happened anyway.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['decision_scientist', 'data_scientist', 'exec'],
    business_problems: ['bp-promotion-effectiveness'],
    tags: ['simulation', 'diagnosis', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-02'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-counterfactual-baseline',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-OPPORTUNITY-WINDOW',
    name: 'Opportunity Window & Micro-Market Graph',
    summary: 'Turns timing into an active decision variable and evaluates micro-market store candidates explainably by catchment, inventory and shopper mission.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['marketing_strategist', 'category_manager', 'store_manager'],
    business_problems: ['bp-promotion-effectiveness'],
    tags: ['detection', 'recommendation', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-03'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-opportunity-window',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-READINESS',
    name: 'Decision Readiness & Resilience',
    summary: 'A six-dimension evaluation producing an explainable readiness verdict, integrated with Decision Ripple rather than standing up a parallel risk engine.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['exec', 'coo', 'decision_scientist'],
    business_problems: ['bp-ai-trust', 'bp-decision-latency'],
    tags: ['human-in-the-loop', 'diagnosis', 'audit-trail'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: ['PAT-RISK-03'],
    delivered_by: ['CDI-04'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-readiness',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-TIMELINE',
    name: 'Decision Timeline & Demand Decomposition',
    summary: 'Renders one closed evaluation over time with progressive driver decomposition, following the What, Why, Evidence, What-If disclosure pattern.',
    capability_type: 'domain-capability',
    domains: ['retail_grocery'],
    personas: ['demand_planner', 'category_manager', 'exec'],
    business_problems: ['bp-forecast-uncertainty'],
    tags: ['explanation', 'diagnosis', 'forecasting'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-05'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-decision-timeline',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-OUTCOME-FRONTIER',
    name: 'Multi-Objective Outcome Frontier',
    summary: 'A Pareto set of candidate campaign configurations over competing objectives, selected by declared constraints only: no weights, no utility function, no model ranking.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'cco', 'decision_scientist'],
    business_problems: ['bp-promotion-effectiveness'],
    tags: ['simulation', 'recommendation', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-06'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-outcome-frontier',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-CONTRACT',
    name: 'Decision Contract & Decision Half-Life',
    summary: 'Binds the exact evidential basis of a decision by reference, digest and snapshot, and reports whether that basis still holds as assumptions and signals evolve.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['cdao', 'decision_scientist', 'enterprise_architect'],
    business_problems: ['bp-ai-trust', 'bp-decision-recall'],
    tags: ['audit-trail', 'human-in-the-loop', 'detection'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-07A'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-decision-contract',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-LEARNING-LOOP',
    name: 'Pre-Mortem, Prediction vs Reality & Closed Learning Loop',
    summary: 'Three bound artefacts: failure modes enumerated before acting, prediction compared with outcome on like-for-like matches only, and learning candidates that never self-promote.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['decision_scientist', 'cdao', 'exec'],
    business_problems: ['bp-decision-recall', 'bp-ai-trust'],
    tags: ['audit-trail', 'human-in-the-loop', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-07B'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-learning-loop',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-INTENT-FUSION',
    name: 'Intent Fusion & Contextualised Decision Outlook',
    summary: 'Fuses commercial intent with the enterprise signal stream into a contextualised outlook, so a plan is read against what the environment is actually doing.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['demand_planner', 'exec', 'decision_scientist'],
    business_problems: ['bp-forecast-uncertainty'],
    tags: ['forecasting', 'diagnosis', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['IFI-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-intent-fusion',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-ENTERPRISE-SIGNAL',
    name: 'Enterprise Signal Contract & Foundation',
    summary: 'The canonical signal contract and taxonomy every CogniX capability reads evidence through, with source classification and provenance carried on the datum.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['enterprise_architect', 'cdao', 'data_scientist'],
    business_problems: ['bp-ai-trust'],
    tags: ['nextjs-api', 'audit-trail', 'detection'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['ESF-1'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-enterprise-signal',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-SIGNAL-SIMULATION',
    name: 'Dynamic Signal Simulation',
    summary: 'Evolves enterprise signals deterministically over time under an active scenario, so a demonstration shows a situation developing rather than a frozen snapshot.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['decision_scientist', 'data_scientist'],
    business_problems: ['bp-forecast-uncertainty'],
    tags: ['simulation', 'detection'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['ESF-2'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-signal-simulation',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-SIGNAL-CONNECTOR',
    name: 'External Signal Connector Contract',
    summary: 'A provider-neutral connector abstraction letting planning, commerce, weather, events and telemetry feeds publish into the canonical signal contract by envelope normalisation.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['enterprise_architect', 'it_service_leader', 'cio'],
    business_problems: ['bp-ai-trust'],
    tags: ['nextjs-api', 'enablement'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['ESF-3'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-signal-connector',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-JOURNEY-TELEMETRY',
    name: 'Journey Telemetry',
    summary: 'Records what a user actually did across a decision journey, so demonstrations and learning rest on observed interaction rather than recollection.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['cdao', 'data_analyst', 'enterprise_architect'],
    business_problems: ['bp-decision-recall'],
    tags: ['audit-trail', 'nextjs-api', 'reporting'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP10-B'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-journey-telemetry',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-MEMORY-LEARNING-API',
    name: 'Memory & Learning API',
    summary: 'The extracted service boundary for enterprise memory and learning patterns, giving every surface one governed way to store and retrieve organisational learning.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['enterprise_architect', 'cdao'],
    business_problems: ['bp-decision-recall'],
    tags: ['nextjs-api', 'audit-trail', 'enablement'],
    demonstrated_by: [],
    originated_as: ['EXP-MEMORY-03'],
    evidenced_by: [],
    delivered_by: ['WP10-D'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-memory-learning-api',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-LEARNING-PATTERN-REGISTRY',
    name: 'Enterprise Learning Pattern Registry',
    summary: 'The canonical store of recognised enterprise learning patterns, matched against a live situation so a recurring shape is recognised rather than rediscovered.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['decision_scientist', 'cdao', 'exec'],
    business_problems: ['bp-decision-recall'],
    tags: ['detection', 'audit-trail', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: ['PAT-COMM-01', 'PAT-OPP-02', 'PAT-RISK-03', 'PAT-RIPPLE-04'],
    delivered_by: ['WP10-D'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-learning-pattern-registry',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-INNOVATION-PORTFOLIO',
    name: 'Innovation Portfolio',
    summary: 'The discovery surface over registered experiments and demonstration solutions: the current answer to what CogniX can do, and the nearest predecessor to the Atlas.',
    capability_type: 'experience',
    domains: [],
    personas: ['exec', 'cco'],
    business_problems: ['bp-capability-discovery'],
    tags: ['enablement', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP2'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-innovation-portfolio',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-EXPERIMENT-CANVAS',
    name: 'Reusable Innovation Canvas',
    summary: 'A single reusable canvas that renders any registered experiment from its metadata, so a new experiment becomes discoverable without a bespoke screen.',
    capability_type: 'experience',
    domains: [],
    personas: ['exec', 'cco'],
    business_problems: ['bp-capability-discovery'],
    tags: ['enablement', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP3'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-experiment-canvas',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-ARCHITECTURE-STORYBOARD',
    name: 'Architectural Storyboard',
    summary: 'A twelve-slide static narrative explaining the platform architecture. Retirement candidate under SB-GATE: it makes no engine or API call and narrates a legacy stack.',
    capability_type: 'experience',
    domains: [],
    personas: ['enterprise_architect', 'cio', 'exec'],
    business_problems: ['bp-capability-discovery'],
    tags: ['static-content', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: 'Retired',
    implementation_status: 'simulated',
    platform_reusable: false,
    knowledge_ref: 'cap-architecture-storyboard',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DECISION-LIFECYCLE-VIEW',
    name: 'Decision Lifecycle Explainer',
    summary: 'A static stage-by-stage account of how a recommendation is produced, from signal detection through scope enforcement to governed write-back.',
    capability_type: 'experience',
    domains: [],
    personas: ['exec', 'cdao', 'enterprise_architect'],
    business_problems: ['bp-ai-trust'],
    tags: ['static-content', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: null,
    implementation_status: 'simulated',
    platform_reusable: false,
    knowledge_ref: 'cap-decision-lifecycle-view',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-CONTRACT-VERIFICATION',
    name: 'Contract Verification',
    summary: 'Lets a reader inspect the governed contract behind a decision: what was bound, by which digest, and whether the narrative matches the artefact.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['cdao', 'decision_scientist', 'enterprise_architect'],
    business_problems: ['bp-ai-trust'],
    tags: ['audit-trail', 'human-in-the-loop', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CDI-07A'],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-contract-verification',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-20',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-AUTH-PLATFORM-SETUP',
    name: 'Authentication & Platform Setup',
    summary: 'Sign-in, registration, password recovery and the post-auth setup step where a demonstrator selects role context and supplies a provider key that is never committed.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['it_service_leader', 'cio', 'enterprise_architect'],
    business_problems: ['bp-access-governance'],
    tags: ['nextjs-api', 'iam', 'enablement'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: null,
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-auth-platform-setup',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-GOVERNANCE-SETTINGS',
    name: 'Governance & Operations Surface',
    summary: 'The operator surface for thresholds, AI options and access scoping. Controls are present; several are demonstration affordances rather than enforced policy.',
    capability_type: 'governance-control',
    domains: [],
    personas: ['cdao', 'it_service_leader', 'enterprise_architect'],
    business_problems: ['bp-access-governance'],
    tags: ['iam', 'human-in-the-loop', 'static-content'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: [],
    lifecycle_state: null,
    implementation_status: 'partially-implemented',
    platform_reusable: false,
    knowledge_ref: 'cap-governance-settings',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-DOMAIN-PERSONA-CONTEXT',
    name: 'Domain & Decision-Lens Context',
    summary: 'Runtime selection of industry domain and decision lens, so the same estate is demonstrated in a client vocabulary without a code change.',
    capability_type: 'enabling-service',
    domains: [],
    personas: ['exec', 'cco', 'enterprise_architect'],
    business_problems: ['bp-capability-discovery'],
    tags: ['enablement', 'explanation'],
    demonstrated_by: [],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['WP1'],
    lifecycle_state: null,
    implementation_status: 'partially-implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-domain-persona-context',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-20',
    updated_at: '2026-08-20',
    reviewed_at: '2026-08-22',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-CONTINUOUS-DECISION-TWIN',
    name: 'Continuous Decision Twin',
    summary: 'One continuous decision journey over a whole campaign horizon — activated baseline, elapsed evidence, projected remainder — with observed, simulated and predicted kept as three declared classes.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'marketing_strategist', 'category_manager', 'demand_planner'],
    business_problems: ['bp-decision-latency', 'bp-decision-recall', 'bp-promotion-effectiveness'],
    tags: ['detection', 'explanation', 'audit-trail', 'human-in-the-loop'],
    demonstrated_by: ['SOL-PROMO-01'],
    originated_as: ['EXP-CDI-01'],
    evidenced_by: [],
    delivered_by: ['CTW-01', 'CTW-01R'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-continuous-decision-twin',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-23',
    updated_at: '2026-08-23',
    reviewed_at: '2026-08-23',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-GOVERNED-FORECAST',
    name: 'Governed Forecast Execution',
    summary: 'Qualified dataset to genuine model execution to forecast, uncertainty and provenance, where the model named to a user is the implementation that produced the numbers and an unregistered name is refused.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['demand_planner', 'data_scientist', 'decision_scientist', 'enterprise_architect'],
    business_problems: ['bp-forecast-uncertainty', 'bp-ai-trust'],
    tags: ['forecasting', 'explanation', 'audit-trail'],
    demonstrated_by: ['SOL-DEMAND-02'],
    originated_as: [],
    evidenced_by: [],
    delivered_by: ['CTW-03', 'FM-01'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-governed-forecast',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-23',
    updated_at: '2026-08-23',
    reviewed_at: '2026-08-23',
    version: '1.0.0'
  },
  {
    capability_id: 'CAP-PREDICTIVE-INTERVENTION',
    name: 'Predictive Intervention Planning',
    summary: 'Derives decision moments from a governed forecast, plans an intervention against a window, reassesses it as evidence arrives, and reforecasts only the remaining horizon once it is confirmed.',
    capability_type: 'platform-capability',
    domains: [],
    personas: ['exec', 'marketing_strategist', 'category_manager', 'supply_chain_planner'],
    business_problems: ['bp-decision-latency', 'bp-promotion-effectiveness'],
    tags: ['recommendation', 'simulation', 'human-in-the-loop', 'audit-trail'],
    demonstrated_by: ['SOL-PROMO-01'],
    originated_as: ['EXP-CDI-01'],
    evidenced_by: [],
    delivered_by: ['CTW-02'],
    lifecycle_state: 'Prototype',
    implementation_status: 'implemented',
    platform_reusable: true,
    knowledge_ref: 'cap-predictive-intervention',
    owner: 'G10X Enterprise Innovation Lab',
    created_at: '2026-08-23',
    updated_at: '2026-08-23',
    reviewed_at: '2026-08-23',
    version: '1.0.0'
  }
];

/** Registry size guard. The registry is a registry; growth belongs in knowledge modules. */
export const REGISTRY_SUMMARY_MAX_LENGTH = 240;
