/**
 * Capability knowledge — CAP-ENTERPRISE-SIGNAL.
 * Authored by ATL-03. Every claim traces to a cited path, test or report;
 * anything not fully real is stated at field level and warned in the demo path.
 */
import { defineKnowledge } from '../authoring';

export const knowledge = defineKnowledge({
  capability_id: 'CAP-ENTERPRISE-SIGNAL',
  description:
    'The canonical enterprise signal contract and taxonomy that every CogniX capability reads evidence through, with source classification and provenance carried on the datum rather than on the page.',
  innovation_thesis:
    'If provenance lives on the page, it is lost the moment the number is copied. Carrying it on the datum is what makes every downstream claim traceable.',
  usage_instructions:
    'Query the signal endpoints for the current stream. Each signal carries its type, source classification and provenance.',
  testing_instructions:
    'Run npx tsx tests/unit/run-signal-tests.ts (6 assertions).',
  field_status: [
    { field: 'confidence', implementation_status: 'simulated', note: 'Demonstration default; never treated as authority under the ESF-6 admission rules.' }
  ],
  architecture_narrative:
    'A canonical OpenAPI and TypeScript contract with a closed signal taxonomy, generated deterministically by the world service and served through a same-origin proxy.',
  architecture_flow: [
    'Signal generation or ingestion',
    'Taxonomy classification',
    'Source and provenance stamping',
    'Same-origin proxy',
    'Consumption by capability engines'
  ],
  apis: [
    { method: 'GET', path: '/api/v1/signals', purpose: 'List signals' },
    { method: 'GET', path: '/api/v1/signals/current', purpose: 'Current signal set' },
    { method: 'GET', path: '/api/v1/signals/health', purpose: 'Service health' }
  ],
  contracts: [
    { name: 'EnterpriseSignal', path: 'packages/contracts/src/enterprise-signal-model.ts', direction: 'out' }
  ],
  data_sources: [
    { name: 'Enterprise World synthetic signal generator', kind: 'synthetic', path: 'services/world/src/enterprise-signal-generator.ts' }
  ],
  implementation_references: [
    { path: 'packages/contracts/src/enterprise-signal-model.ts', note: 'Contract' },
    { path: 'services/world/src/enterprise-signal-generator.ts', note: 'Generator' },
    { path: 'lib/enterprise-signal-client.ts', note: 'Client' },
    { path: 'app/api/v1/signals/route.ts', note: 'API' }
  ],
  validation_evidence: [
    { kind: 'test', ref: 'tests/unit/run-signal-tests.ts', outcome: '6 assertions on contract conformance.', observed_at: '2026-08-20', observed_by: 'ATL-03 reconciliation' },
    { kind: 'report', ref: 'docs/reports/COGNIX_ESF_1_ENTERPRISE_SIGNAL_FOUNDATION_REPORT.md', outcome: 'Completion report.', observed_at: '2026-08-20', observed_by: 'ATL-03 reconciliation' }
  ],
  test_runners: [
    'tests/unit/run-signal-tests.ts'
  ],
  known_limitations: [
    { limitation: 'Every signal in the estate is generated by the synthetic world. No production feed is connected.', severity: 'high' },
    { limitation: 'Confidence and quality defaults are demonstration constants and are explicitly not authority.', severity: 'high' }
  ],
  use_cases: [
    { title: 'Giving every capability one evidence contract', context: 'Each capability invents its own notion of evidence.', outcome: 'One contract, one taxonomy, provenance on the datum.' }
  ],
  demo_scenarios: [
    {
      path_type: 'three-minute',
      title: 'One evidence contract',
      audience: 'enterprise_architect',
      duration_mins: 3,
      steps: [
        { action: 'Query the signal stream', what_to_say: 'Every capability reads evidence through this one contract, and provenance travels with the datum.', what_to_show: 'A signal with its classification and provenance', expected_observation: 'Provenance on the record itself' }
      ],
      prerequisites: [],
      warnings: [
        'All signals are synthetic. No production feed is connected.'
      ],
      follow_ups: []
    }
  ],
  client_questions: [
    { question: 'How would our data get in?', audience: 'enterprise_architect', difficulty: 'medium' }
  ],
  cross_domain_applicability: [
    { domain_id: 'manufacturing', applicability: 'likely', rationale: 'A canonical signal contract is deliberately industry-neutral.' },
    { domain_id: 'energy_utilities', applicability: 'hypothetical', rationale: 'Plausible for telemetry-rich domains; not assessed.' }
  ],
  related_capabilities: [
    { ref: 'CAP-INTENT-FUSION', relation: 'enables' },
    { ref: 'CAP-OBSERVATION-CORRESPONDENCE', relation: 'enables' },
    { ref: 'CAP-SIGNAL-CONNECTOR', relation: 'enables' },
    { ref: 'CAP-SIGNAL-SIMULATION', relation: 'enables' }
  ],
  related_governance: [
    'docs/governance/ENTERPRISE_SIGNAL_MODEL.md'
  ],

  /**
   * The order is the argument. Classification and provenance stamping happen before anything
   * consumes the signal, which is precisely why a downstream claim stays traceable after the
   * number has been copied somewhere else — prose states that as a principle, the pipeline shows
   * it as a position. The first stage also keeps the standing limitation in view: the stream in
   * this estate is synthetic.
   */
  visualisation: {
    kind: 'flow',
    concept: 'Carrying Provenance on the Datum',
    nodes: [
      { label: 'Generation or ingestion', detail: 'The world service today, with no production feed connected', role: 'stage' },
      { label: 'Taxonomy classification', detail: 'Placed within the closed signal taxonomy', role: 'stage' },
      { label: 'Source and provenance stamped', detail: 'Carried on the datum, never on the page', role: 'stage' },
      { label: 'Same-origin proxy', detail: 'One route the estate reads the stream through', role: 'stage' },
      { label: 'Consumption by engines', detail: 'Every capability reads evidence through this one contract', role: 'stage' }
    ],
    description:
      'An ordered pipeline: a signal is generated or ingested, classified within the closed taxonomy, then stamped with its source classification and provenance before it is served through the same-origin proxy and consumed by capability engines. The stamping sits ahead of consumption, so provenance travels on the datum rather than on the page and survives being copied. In this estate the first stage is the synthetic world service; no production feed is connected.'
  },
});
